services:
    database:
        image: mariadb
        environment:
            MYSQL_DATABASE: todolist_db
            MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: "yes"
        volumes:
            - db_data:/var/lib/mysql
            - /home/thomas/projet-eni/backend/scriptSQL.sql:/docker-entrypoint-initdb.d/scriptSQL.sql \
        ports:
            - "3306:3306"

    frontend:
        image: thomasdeo/frontend-projet-eni:latest
        ports:
            - "80:80"

    backend:
        image: thomasdeo/backend-projet-eni:latest
        environment:
            - DB_HOST=database
            - DB_USER=root
            - DB_PASSWORD=
            - DB_NAME=todolist_db
            - DB_DIALECT=mysql
            - PORT=3000
        ports:
            - "3000:3000"

volumes:
    db_data:
