apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kv-mariadb
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"                   # true si tu utilises Managed Identity
    useVMManagedIdentity: "true"              # si tu relies ton AKS à un user-assigned MI
    userAssignedIdentityID: "dd0fea37-b6a1-47eb-a12c-62cd28b3d2d7"  # l'ID de ton Managed Identity
    keyvaultName: "keyvault-projet-eni"
    cloudName: ""
    objects: |
      array:
        - |
          objectName: mysql-flexible-admin-password
          objectType: secret
          objectVersion: ""
    tenantId: "7f4f3591-5f6c-4f7b-a1bd-0a2dd8831218"
  secretObjects:                              # permet de créer un Secret K8s automatiquement
    - secretName: backend-secret
      type: Opaque
      data:
        - objectName: mysql-flexible-admin-password
          key: backend-secret
