apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kv-grafana
  namespace: monitoring
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "dd0fea37-b6a1-47eb-a12c-62cd28b3d2d7"
    keyvaultName: "keyvault-projet-eni"
    cloudName: ""
    objects: |
      array:
        - |
          objectName: grafana-admin-password
          objectType: secret
          objectVersion: ""
    tenantId: "7f4f3591-5f6c-4f7b-a1bd-0a2dd8831218"
  secretObjects:
    - secretName: grafana-admin
      type: Opaque
      data:
        - objectName: grafana-admin-password
          key: admin-password
