name: Build Frontend Docker Image

on:
  push:
    branches: [ "main" ]
    paths:
      - 'frontend/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - name: Run tests
        working-directory: ./frontend
        continue-on-error: true
        run: |
          npm install
          npx ng test --watch=false --browsers=ChromeHeadless

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/frontend-projet-eni:latest

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.29.0'

      - name: AKS Login
        uses: azure/aks-set-context@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          cluster-name: <nom-du-cluster>
          resource-group: <nom-du-resource-group>

      - name: Reload AKS Deployment
        run: |
          kubectl set image deployment/frontend frontend=${{ secrets.DOCKER_USERNAME }}/frontend-projet-eni:latest -n <namespace>
          kubectl rollout status deployment/frontend -n <namespace>
